name: 'Build and Publish'
description: 'Build and Publish'
inputs:
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
