on:
  push:
    branches:
    - master
name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Build and Publish'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      uses: ./.github/actions/docker/
      with:
        username: ${{ secrets.GITHUB_USERNAME }}
        password: ${{ secrets.GITHUB_PASSWORD }}
